# Spring配置
spring:
  # 选用配置文件
  profiles:
    active: prod
  datasource:
    # 数据源配置
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 扩展插件
    # 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    druid:
      filters: stat
      # 最大连接池数量
      maxActive: 20
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 8
      # 获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 最小连接池数量
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
      validationQuery: select count(1) from user
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 是否缓存preparedStatement，即PSCache
      poolPreparedStatements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      maxOpenPreparedStatements: -1
      stat-view-servlet:
        url-pattern: /druid/*
        # 登录用户名/密码
        login-username: root
        login-password: 123456
  servlet:
    multipart:
      # 修改文件最大上传限制
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    # json返回日期格式
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatisPlus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
